# -*- coding: utf-8 -*-
"""navie assign.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4SfKUVFPkPm6NKQ_lvHVI1mWUAhBRdm
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

sal_train=pd.read_csv("SalaryData_Train.csv")
sal_train.head(10)

sal_test=pd.read_csv('SalaryData_Test.csv')
sal_test.head(10)

sal_test.columns

sal_train.columns

sal_test.shape

sal_train.shape

sal_test.info()

sal_train.info()

sal_test.describe()

sal_train.describe()

string_col=['workclass','education','maritalstatus','occupation','relationship','race','sex','native']
string_col

from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
for i in string_col:
    sal_train[i]=label_encoder.fit_transform(sal_train[i])
    sal_test[i]=label_encoder.fit_transform(sal_test[i])

columns=list(sal_train.columns)
columns

train_x=sal_train[columns[0:13]]
train_x

train_y=sal_train[columns[13]]
train_y

test_x=sal_test[columns[0:13]]
test_x

test_y=sal_train[columns[13]]
test_y

train_x=sal_train.iloc[0:600,0:13]
train_y=sal_train.iloc[0:600,13]

test_x=sal_test.iloc[:,0:13]
test_y=sal_test.iloc[:,13]

#Naive Bayes Classifier
clf = MultinomialNB()
clf.fit(train_x,train_y)
clf.score(test_x,test_y)
y_pred = clf.predict(test_x)
print(classification_report(test_y, y_pred))

